version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sample-app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_PORT: 5432
    volumes:
      - ./state/database:/var/lib/postgresql/data
    restart: on-failure